# Generated by Django 2.2.3 on 2019-07-11 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, '---'), (2, '가방'), (3, '전자기기'), (4, '지갑'), (5, '학용품'), (6, '기타')], default=1, verbose_name='종류')),
                ('title', models.CharField(max_length=100, verbose_name='분실물')),
                ('whenGet', models.CharField(default='', max_length=100, verbose_name='분실/습득 시간')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='이미지')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='슬러그')),
                ('type', models.IntegerField(choices=[(1, '---'), (2, '분실'), (3, '습득')], default=1, verbose_name='분실/습득')),
                ('description', models.TextField(verbose_name='설명')),
                ('active', models.BooleanField(default=True, verbose_name='찾음')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_products', to='lost.Category', verbose_name='분실/습득 장소')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_products', to=settings.AUTH_USER_MODEL, verbose_name='아이디')),
            ],
        ),
    ]
