# Generated by Django 2.2.3 on 2019-07-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(default='', max_length=100, verbose_name='분실물'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='제목'),
        ),
    ]
