# Generated by Django 2.2.3 on 2019-07-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0005_auto_20190715_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='writer',
        ),
    ]
